pid /tmp/pqjobs-nginx.pid;
error_log /tmp/pqjobs-nginx-error.log;

events {
    worker_connections 1024;
}

http {
    access_log /tmp/pqjobs-nginx-access.log;
    types_hash_max_size 2048;
    types_hash_bucket_size 128;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    include /mnt/disk2/job-PhuQuoc/deploy/nginx/pqjobs-backend.local.conf;
}
