from copilotkit import CopilotKitState
from typing import Optional, List, Any, Dict


class CandidateState(CopilotKitState):
    # Auth
    authorization: Optional[Dict[str, Any]] = None

    # Worker progress shared with frontend
    activeWorker: Optional[str] = None  # career_advisor, job_searcher, cv_designer
    currentStep: str = ""
    status: str = "idle"  # idle, thinking, running, waiting_user, done, error
    toolStatus: Optional[str] = None

    # CV Flow control
    cv_flow: str = "idle"  # idle, collecting, generating, preview, editing, done
    step: str = ""
    progress: int = 0

    # User info (collected during conversation)
    user_name: Optional[str] = None
    user_email: Optional[str] = None
    user_phone: Optional[str] = None
    user_address: Optional[str] = None
    user_summary: Optional[str] = None
    user_skills: List[str] = []
    user_education: List[Dict[str, Any]] = []
    user_experience: List[Dict[str, Any]] = []
    user_projects: List[Dict[str, Any]] = []
    user_languages: List[str] = []

    # Template (generated by agent, synced to FE via shared state)
    current_template_id: Optional[str] = None
    current_template_name: Optional[str] = None
    current_template_html: Optional[str] = None
    current_template_css: Optional[str] = None

    # Resume (after save)
    current_resume_id: Optional[str] = None
